### ISSUE TITLE
Support Perl Versions before 5.10!

### ISSUE THREAD

**Issue by bluefeet** [dagolden/data-uuid-mt#1]
Hey - I'd love to use this module, but it errors out when I try to install it with:

```
Perl v5.10.0 required--this is only v5.8.9, stopped at Makefile.PL line 5.
```

Are you open to the idea of supporting at least 5.8?  A lot of people are still on 5.8.

If you're open to this I'd be happy to make the change.

**Comment by dagolden** [comment]
Unfortunately, the module uses byte-order modifiers to pack() which were only introduced in Perl 5.10.  If you want to work up an equivalent that doesn't use those and that does not have any performance decrease, I'd be willing to consider it.

**Comment by bluefeet** [comment]
Gah, OK, I was hoping it was just a stylistic thing.  I'll just use UUID for now and move to this module once we're upgraded to 5.10+.  Thanks!
